name: Feature/Bugfix

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: build and test
        env:
          VERSION_CODE: ${{ github.run_number }}
        run: ./gradlew clean testDebug assembleDebug
      - name: build and test
          env:
            VERSION_CODE: ${{ github.run_number }}
          run: ./gradlew clean testDebug assembleDebug
      - name: publish package
        run: gradle publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}